import Head from "next/head";
import Carrousel from "../components/Carrousel/Carrousel";
import CategoryGrid from "src/components/Grids/CategoryGrid/CategoryGrid";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { dominio } from "src/utils/consts";
import SaleGrid from "src/components/Grids/SaleGrid/SaleGrid";
export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rispot Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rispot Check</h1>
        <h3>Una web de análisis</h3>

        <SaleGrid array={data} />
        {/* <CategoryGrid array={Categories} /> */}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(`http://${dominio}/api/sales`);
  const data = await res.json();
  console.log(data);
  return {
    props: {
      data,
    },
  };
}
