import Head from "next/head";
import Carrousel from "../components/Carrousel/Carrousel";
import Grid from "src/components/Grid/Grid";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Rispot Check</h1>
        <h3>Una web de análisis</h3>
        <Carrousel />
        <Grid />
      </main>
    </div>
  );
}
